[package]
name = "rdkafka"
version = "0.1.1"
authors = ["Federico Giraud <giraud.federico@gmail.com>"]
repository = "https://github.com/fede1024/rust-rdkafka"
readme = "README.md"
license = "MIT"
description = "Rust wrapper for librdkafka"
keywords = ["kafka", "rdkafka"]

[dependencies]
librdkafka-sys = { path = "librdkafka-sys", version = "0.9.2-0" }
errno = "^0.1.8"
futures = "^0.1.3"
libc = "^0.2.0"
log = "^0.3.0"
env_logger = "^0.3.0"
thread-id = "^3.0.0"

[features]
default = ["zlib"]

zlib = ["librdkafka-sys/zlib"]
ssl = ["librdkafka-sys/ssl"]
sasl = ["librdkafka-sys/sasl", "ssl"]
