[package]
name = "rdkafka"
version = "0.10.0"
authors = ["Federico Giraud <giraud.federico@gmail.com>"]
repository = "https://github.com/fede1024/rust-rdkafka"
readme = "README.md"
license = "MIT"
description = "Rust wrapper for librdkafka"
keywords = ["kafka", "rdkafka"]
categories = ["api-bindings"]

[dependencies]
rdkafka-sys = { path = "rdkafka-sys", version = "0.9.5-0" }
env_logger = "^0.3.0"
errno = "^0.1.8"
futures = "^0.1.13"
libc = "^0.2.0"
log = "^0.3.0"
serde = "^0.9.8"
serde_derive = "^0.9.8"
serde_json = "^0.9.8"

[dev-dependencies]
clap = "^2.18.0"
tokio-core = "^0.1.4"
futures-cpupool = "^0.1.2"
rand = "^0.3.15"
chrono = "^0.3.1"

[features]
default = []

ssl = ["rdkafka-sys/ssl"]
sasl = ["rdkafka-sys/sasl", "ssl"]
